routes/web.php
<?php

use App\Models\Recipe;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\Admin\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [RecipeController::class, 'all'])->name('welcome');

Route::post('authenticate', [LoginController::class, 'authenticate'])->name('authenticate');

//user must be authorized and email must be verified to access these routes
Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('/search/', [RecipeController::class, 'search'])->name('search');
    Route::resource('recipes', RecipeController::class);
    // Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
});

// only admins can access these routes. isAdmin gate defined in authserviceprovider; middleware adminaccess
Route::middleware(['auth', 'auth.isAdmin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/reject/{recipe_id}', [DashboardController::class, 'reject'])->name('recipe.reject.page');
    Route::patch('/approve-recipe/{recipe_id}', [RecipeController::class, 'approve'])->name('recipe.approve');
    Route::patch('/reject-recipe/{recipe_id}', [RecipeController::class, 'reject'])->name('recipe.reject');

});

app/Models/Recipe.php
<?php

namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Recipe extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'name',
        'type',
        'summary',
        'description',
        'main_ingredient',
        'ingredients',
        'image',
        'nutritional_value',
        'cost',
        'approval_status',
        'comments',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }


} 

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Recipe;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Recipe\UpdateRecipeRequest;
use App\Http\Requests\Recipe\CreateRecipesRequest;

class RecipeController extends Controller
{

    public function all()
    {
        $recipes = Recipe::where('approval_status', 1)->get();
        return view('welcome')->with('recipes', $recipes);

    }
    /**
     * Display a listing of the resource per user.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = Auth::id(); 
        // dd(Recipe::where('user_id', $user_id));

        $recipes = Recipe::where('user_id', $user_id)->get();
        return view('recipes.index')->with('recipes', $recipes);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('recipes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRecipesRequest $request)
    {
        $user_id = Auth::id(); 

        $image = $request->image->store('recipes');

        // Create post
        $recipe = Recipe::create([
            'user_id' => $user_id,
            'name' => $request->name,
            'type' => $request->type,
            'summary' => $request->summary,
            'description' => $request->description,
            'main_ingredient' => $request->main_ingredient,
            'ingredients' => $request->ingredients,
            'image' => $image,
            'nutritional_value' => $request->nutritional_value,
            'cost' => $request->cost,   
        ]);

        // Flash success message
        session()->flash('success', 'Recipe Added Successfully!');

        // Redirect user
        return redirect(route('recipes.index'));
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Recipe $recipe)
    {
        return view('recipes.show')->with('recipe', $recipe);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Recipe $recipe)
    {
        return view('recipes.create')->with('recipe', $recipe);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRecipeRequest $request, Recipe $recipe)
    {

        $data = $request->only(['name', 'type', 'summary', 'description', 'main_ingredient', 'ingredients', 'nutritional_value', 'cost']);

        // check for new image
        if ($request->hasFile('image')) {
            // upload it
            $image = $request->image->store('recipes');

            // delete old image
            $recipe->deleteImage();

            $data['image'] = $image;
        }

        // update attributes
        $recipe->update($data);

        // flash message
        session()->flash('success', 'Recipe Updated Successfully');

        // redirect user
        return redirect(route('recipes.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function search(Request $request){
        // Get the search value from the request
        $search = $request->search;

        // Search all necessary columns from the recipes table
        $recipes = Recipe::query()
            ->where('approval_status', true)
            ->where('name', 'LIKE', "%{$search}%")
            ->orWhere('type', 'LIKE', "%{$search}%")
            ->orWhere('summary', 'LIKE', "%{$search}%")
            ->orWhere('description', 'LIKE', "%{$search}%")
            ->orWhere('main_ingredient', 'LIKE', "%{$search}%")
            ->orWhere('ingredients', 'LIKE', "%{$search}%")
            ->orWhere('nutritional_value', 'LIKE', "%{$search}%")
            ->get();
    
        // Return the search view with the resluts compacted
        return view('recipes.search', compact('recipes'));
    }

    public function approve($id)
    {
        $recipe = Recipe::findorFail($id);

        $recipe->update(['approval_status' => true]);
        $recipe->save();

        return redirect(route('admin.dashboard'));
    }

    public function reject(Request $request, Recipe $recipe)
    {
        $recipe = Recipe::findorFail($request->id);

        // $data = $request->only(['comments']);
        // $data['approval_status'] = false;

        $recipe->update(['approval_status' => false, 'comments' => $request->comments]);
        $recipe->save();

        // $recipe->save();

        // flash message
        session()->flash('success', 'Recipe Rejected Successfully');

        return redirect(route('admin.dashboard'));
    }

}

resources/views/recipes/create.blade.php
@extends('templates.main')

@section('css')

@endsection

@section('content')

<div class="card card-default">
    <div class="card-header">
        <h4>{{ isset($recipe) ? 'Edit Recipe' : 'Create Recipe' }}</h4>
        
    </div>
    <div class="card-body p-5">
        @include('partials.errors')
        <form class="p-2" action="{{ isset($recipe) ? route('recipes.update', $recipe->id) : route('recipes.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            @if(isset($recipe))
            @method('PUT')
            @endif
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" id="name" class="form-control" name="name" value="{{ isset($recipe) ? $recipe->name : '' }}">
            </div>

            <div class="mb-3">
                <label for="type" class="form-label">Meal Type</label>
                <input type="text" id="type" class="form-control" name="type" value="{{ isset($recipe) ? $recipe->type : '' }}" placeholder="Breakfast, Lunch, Dinner ...">
            </div>

            <div class="mb-3">
                <label for="summary" class="form-label">Summary</label>
                <textarea name="summary" id="summary" cols="5" rows="2" class="form-control">{{ isset($recipe) ? $recipe->summary : '' }}</textarea>
            </div>

            <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <input id="description" type="hidden" name="description" value="{{ isset($recipe) ? $recipe->description : '' }}" />
                <trix-editor input="description"></trix-editor>
            </div>

            <div class="mb-3">
                <label for="main_ingredient" class="form-label">Main Ingredient</label>
                <input type="text" id="main_ingredient" class="form-control" name="main_ingredient" value="{{ isset($recipe) ? $recipe->main_ingredient : '' }}">
            </div>

            <div class="mb-3">
                <label for="ingredients" class="form-label">Ingredients</label>
                <input id="ingredients" type="hidden" name="ingredients" value="{{ isset($recipe) ? $recipe->ingredients : '' }}" />
                <trix-editor input="ingredients"></trix-editor>
            </div>

            <div class="mb-3">
                <label for="nutritional_value" class="form-label">Nutritional Value</label>
                <input id="nutritional_value" type="hidden" name="nutritional_value" value="{{ isset($recipe) ? $recipe->nutritional_value : '' }}" />
                <trix-editor input="nutritional_value"></trix-editor>
            </div>

            <div class="mb-3">
                <label for="cost" class="form-label">Estimated Cost</label>
                <input type="text" id="cost" class="form-control" name="cost" value="{{ isset($recipe) ? $recipe->cost : '' }}" step=".01">
            </div>

            <div class="mb-3">
                <label for="image" class="form-label">Image</label>
                @if(isset($recipe))
                <img src="{{ asset('storage/'.$recipe->image) }}" alt="recipe image" style="width: 100%">
                @endif

                <input type="file" id="image" class="form-control" name="image">
            </div>

            <div class="mb-3">
                <button class="btn btn-success">{{ isset($recipe) ? 'Update Recipe' : 'Add Recipe' }}</button>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')
@endsection

resources/views/recipes/index.blade.php
@extends('templates.main')

@section('content')

<div class="card card-default px-4 py-5">
    <div class="card-header">
        <h4>Recipes</h4>
    </div>
    <div class="card-body">
        @if($recipes->count() > 0)
        <div class="d-flex justify-content-end mb-2">
            <a href="{{ route('recipes.create') }}" class="btn btn-success float-right">Add Recipes</a>
        </div>

        <table class="table">
            <thead>
                <th scope="col">Image</th>
                <th scope="col">Name</th>
                <th scope="col">Summary</th>
                <th scope="col">Approval Status</th>
                <th></th>
            </thead>

            <tbody>
                @foreach($recipes as $recipe)
                <tr scope="row">
                    <td>
                        <img src="{{ asset('/storage/'.$recipe->image) }}" alt="img" width="120px" height="60px">
                    </td>

                    <td>
                        {{ $recipe->name }}
                    </td>

                    <td>
                        {{ $recipe->summary }}
                    </td>
                    <td>
                        @if($recipe->approval_status)
                            Approved
                        @elseif(is_null($recipe->approval_status))
                            Not approved
                        @else
                            Rejected
                        @endif
                    </td>

                    <td scope="row" class="">
                        <div class="d-flex">
                            <a href="{{ route('recipes.show', $recipe->id) }}" class="btn btn-info btn-sm mr-4" role="button">View</a>
                        @if(is_null($recipe->approval_status))
                            <a href="{{ route('recipes.edit', $recipe->id) }}" class="btn btn-secondary btn-sm ml-2" role="button">Edit</a>
                        @endif
                        </div>
                    </td>

                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <h1 class="text-center display-5 m-3 mb-5">No Recipes At The Moment...</h1>

        <div class="d-flex justify-content-end mb-2">
            <a href="{{ route('recipes.create') }}" class="btn btn-success float-right">Add Recipes</a>
        </div>

        @endif

    </div>
</div>

@endsection

resources/views/recipes/reject.blade.php
@extends('templates.main')

@section('css')

@endsection

@section('content')

<div class="card card-default">
    <div class="card-header">
        <h4>Reject {{ $recipe->name }} Recipe</h4>
    </div>
    <div class="card-body p-5">
        @include('partials.errors')
        <form class="p-2" action="{{ route('admin.recipe.reject', $recipe->id) }}" method="POST" enctype="multipart/form-data">
            @csrf

            @if(isset($recipe))
            @method('PATCH')
            @endif
            <input type="hidden" name="id" value="{{$recipe->id}}">
            <div class="mb-3">
                <label for="comments" class="form-label">Comments</label>
                <textarea name="comments" id="comments" cols="5" rows="5" class="form-control"></textarea>
            </div>

            <div class="mb-3">
                <button class="btn btn-danger">Reject Recipe</button>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')
@endsection

resources/views/recipes/search.blade.php
@extends('templates.main')

@section('content')

<div class="card card-default px-4 py-5">
    <div class="card-header">
        <h4>Recipes Search</h4>
    </div>
    <div class="card-body">
        @if($recipes->count() > 0)

        <table class="table">
            <thead>
                <th scope="col">Image</th>
                <th scope="col">Name</th>
                <th scope="col">Summary</th>
                <th></th>
            </thead>

            <tbody>
                @foreach($recipes as $recipe)
                <tr scope="row">
                    <td>
                        <img src="{{ asset('/storage/'.$recipe->image) }}" alt="img" width="120px" height="60px">
                    </td>

                    <td>
                        {{ $recipe->name }}
                    </td>

                    <td>
                        {{ $recipe->summary }}
                    </td>

                    <td scope="row" class="">
                        <div class="d-flex">
                            <a href="{{ route('recipes.show', $recipe->id) }}" class="btn btn-info btn-sm mr-4" role="button">View</a>
                        </div>
                    </td>

                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <h1 class="text-center display-5 m-3 mb-5">No Recipes Found</h1>

        @endif

    </div>
</div>

@endsection

resources/views/recipes/show.blade.php
@extends('templates.main')

@section('css')
<style>
trix-editor, 
trix-toolbar {
  pointer-events: none;
}
</style>
@endsection

@section('content')
<div class="card card-default">
    <div class="card-header">
        <h4>{{ isset($recipe) ? $recipe->name : '' }}</h4>
        
    </div>
    <div class="card-body p-5">
        <form class="p-2" action="#" method="POST" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="type" class="form-label">Meal Type</label>
                <input type="text" id="type" class="form-control" name="type" value="{{ isset($recipe) ? $recipe->type : '' }}" placeholder="Breakfast, Lunch, Dinner ..." disabled>
            </div>

            <div class="mb-3">
                <label for="summary" class="form-label">Summary</label>
                <textarea name="summary" id="summary" cols="5" rows="2" class="form-control" disabled>{{ isset($recipe) ? $recipe->summary : '' }}</textarea>
            </div>

            <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <input id="description" type="hidden" name="description" value="{{ isset($recipe) ? $recipe->description : '' }}" disabled/>
                <trix-editor input="description" disabled></trix-editor>
            </div>

            <div class="mb-3">
                <label for="main_ingredient" class="form-label">Main Ingredient</label>
                <input type="text" id="main_ingredient" class="form-control" name="main_ingredient" value="{{ isset($recipe) ? $recipe->main_ingredient : '' }}" disabled>
            </div>

            <div class="mb-3">
                <label for="ingredients" class="form-label">Ingredients</label>
                <input id="ingredients" type="hidden" name="ingredients" value="{{ isset($recipe) ? $recipe->ingredients : '' }}" disabled/>
                <trix-editor input="ingredients" disabled></trix-editor>
            </div>

            <div class="mb-3">
                <label for="nutritional_value" class="form-label">Nutritional Value</label>
                <input id="nutritional_value" type="hidden" name="nutritional_value" value="{{ isset($recipe) ? $recipe->nutritional_value : '' }}" disabled/>
                <trix-editor input="nutritional_value" disabled></trix-editor>

            </div>

            <div class="mb-3">
                <label for="cost" class="form-label">Estimated Cost</label>
                <input type="text" id="cost" class="form-control" name="cost" value="{{ isset($recipe) ? $recipe->cost : '' }}" step=".01" disabled>
            </div>

            <div class="mb-3">
                <label for="image" class="form-label">Image</label>
                @if(isset($recipe))
                <img src="{{ asset('storage/'.$recipe->image) }}" alt="recipe image" style="width: 100%">
                @endif
            </div>
            @if($recipe->approval_status === 0)
                <div class="mb-3">
                    <label for="comments" class="form-label">Rejection Comments</label>
                    <textarea name="comments" id="comments" cols="5" rows="5" class="form-control" disabled>{{ isset($recipe) ? $recipe->comments : '' }}</textarea>
                </div>

            @endif
        </form>
    </div>
</div>

@endsection